Repository UMC-Closit/BackEnd, pull requests merged in 2025-05, with the labels that each got.

#222 feat: 사용자 차단 목록 조회
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/repository/UserBlockRepository.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
Labels: ✨feature

#226 feat: 오늘의 옷장 정렬 (최신순, 조회순)
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/controller/TodayClosetController.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/converter/TodayClosetConverter.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/entity/TodayCloset.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/repository/TodayClosetRepository.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/service/TodayClosetQueryService.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/service/TodayClosetQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/service/TodayClosetServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#229 feat: 아이디 및 비밀번호 찾기 기능 구현
  src/main/java/UMC_7th/Closit/domain/emailtoken/controller/EmailTokenController.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/dto/EmailTokenRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/dto/EmailTokenResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/entity/EmailToken.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/repository/EmailTokenRepository.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/service/EmailService.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/service/EmailServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/service/EmailTokenService.java
  src/main/java/UMC_7th/Closit/domain/emailtoken/service/EmailTokenServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/highlight/controller/HighlightController.java
  src/main/java/UMC_7th/Closit/domain/mail/controller/MailController.java
  src/main/java/UMC_7th/Closit/domain/mail/service/MailService.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserAuthController.java
  src/main/java/UMC_7th/Closit/domain/user/dto/PasswordResetRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC_7th/Closit/global/apiPayload/exception/handler/EmailEncodingHandler.java
  src/main/java/UMC_7th/Closit/global/apiPayload/exception/handler/EmailSendHandler.java
  src/main/java/UMC_7th/Closit/global/apiPayload/exception/handler/EmailTemplateLoadHandler.java
  src/main/java/UMC_7th/Closit/global/apiPayload/exception/handler/EmailTokenHandler.java
  src/main/java/UMC_7th/Closit/global/util/HtmlTemplateUtil.java
  src/main/java/UMC_7th/Closit/security/SecurityConfig.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtAuthenticationFilter.java
  src/main/resources/templates/email/email-verification-failed.html
  src/main/resources/templates/email/email-verification-success.html
  src/main/resources/templates/email/verification-template.html
Labels: ✨feature

#228 feat: 사용자 신고 기능 구현
  build.gradle
  src/main/java/UMC_7th/Closit/domain/report/controller/ReportController.java
  src/main/java/UMC_7th/Closit/domain/report/dto/ReportRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/report/repository/ReportRepository.java
  src/main/java/UMC_7th/Closit/domain/report/service/ReportService.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/repository/UserRepository.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/test/java/UMC_7th/Closit/domain/report/service/ReportServiceTest.java
Labels: ✨feature

#233 fix: 배포 오류
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/test/java/UMC_7th/Closit/domain/report/service/ReportServiceTest.java
Labels: 🐛bug

#232 feat: 사용자 차단 여부 조회 구현
  src/main/java/UMC_7th/Closit/domain/emailtoken/controller/EmailTokenController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/entity/Block.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/entity/UserBlock.java
  src/main/java/UMC_7th/Closit/domain/user/repository/BlockRepository.java
  src/main/java/UMC_7th/Closit/domain/user/repository/UserBlockRepository.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
Labels: ✨feature

#234 feat: 배틀 상세 보기
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleCommentController.java
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleController.java
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleLikeController.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Battle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/BattleSorting.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/BattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryServiceImpl.java
Labels: ✨feature

#236 feat: 게시글 정렬 (최신순, 조회순)
  src/main/java/UMC_7th/Closit/domain/post/controller/BookmarkController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/CommentController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/HistoryController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/LikeController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/entity/PostSorting.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/controller/TodayClosetController.java
Labels: ✨feature

#241 feat: 챌린지 배틀 미리보기
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleController.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Battle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/ChallengeBattle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/enums/BattleSorting.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/enums/BattleStatus.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/enums/ChallengeStatus.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/BattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/ChallengeBattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryServiceImpl.java
Labels: ✨feature

#243 fix: LASTEST -> LATEST 오타 수정
  .github/ISSUE_TEMPLATE/bug-report-template.md
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/entity/PostSorting.java
Labels: 🐛bug

#245 fix: 챌린지 배틀 게시판에 내 배틀 게시글 조회 가능 오류
  src/main/java/UMC_7th/Closit/domain/battle/repository/BattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryServiceImpl.java
Labels: 🐛bug

#246 feat: 게시글 친구 공개
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#247 feat: 아이템 태그 검색 기능 구현
  build.gradle
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/HashtagDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/ItemTagDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Hashtag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/ItemTag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/post/entity/PostHashtag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/PostItemTag.java
  src/main/java/UMC_7th/Closit/domain/post/repository/HashtagRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/ItemTagRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostHashtagRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostItemTagRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#256 refactor: 배포 시간 리팩토링
  .github/workflows/deploy.yml
Labels: ♻️refactor, 🌏deploy

#251 feat: 사용자 탈퇴 및 7일 유예 기간 적용
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/repository/UserRepository.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserWithdrawalScheduler.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC_7th/Closit/global/apiPayload/exception/GeneralException.java
  src/test/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImplTest.java
Labels: ✨feature
