Repository UMC-Closit/BackEnd, pull requests merged in 2025-07, with the labels that each got.

#278 feat: 해시태그, 하이라이트, 팔로우 관련 더미 데이터 생성 코드
  src/main/java/UMC_7th/Closit/domain/battle/init/BattleInit.java
  src/main/java/UMC_7th/Closit/domain/battle/init/ChallengeBattleInit.java
  src/main/java/UMC_7th/Closit/domain/follow/init/FollowInit.java
  src/main/java/UMC_7th/Closit/domain/highlight/init/HighlightInit.java
  src/main/java/UMC_7th/Closit/domain/post/init/HashtagInit.java
  src/main/java/UMC_7th/Closit/domain/post/init/ItemTagInit.java
  src/main/java/UMC_7th/Closit/domain/post/init/PostHashtagInit.java
  src/main/java/UMC_7th/Closit/domain/post/init/PostInit.java
  src/main/java/UMC_7th/Closit/domain/post/init/PostItemTagInit.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/init/UserInit.java
Labels: ✨feature

#283 feat: 좋아요 목록 조회
  src/main/java/UMC_7th/Closit/domain/post/controller/LikeController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/LikeConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/LikeResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/repository/LikeRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeService.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeServiceImpl.java
Labels: ✨feature

#292 fix: 파라미터 명 명시 및 차단 목록 조회 코드 수정
  build.gradle
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/repository/BlockRepository.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
Labels: 🚨hotfix

#294 fix: 게시글 부모 댓글 ID response 포함
  src/main/java/UMC_7th/Closit/domain/post/converter/CommentConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/CommentResponseDTO.java
Labels: 🚨hotfix

#299 feat: 배틀, 게시글 response 수정
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/converter/TodayClosetConverter.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/dto/TodayClosetResponseDTO.java
Labels: ✨feature

#303 refactor: 사용자 관련 코드 리팩토링
  build.gradle
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserAccountController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserAuthController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserContentController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserInteractionController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/service/CustomUserDetailService.java
  src/main/java/UMC_7th/Closit/domain/user/service/GoogleOAuthService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserUtil.java
  src/main/java/UMC_7th/Closit/security/SecurityConfig.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtAuthenticationFilter.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtTokenProvider.java
Labels: ♻️refactor

#307 fix: 차단 여부 조회 수정
  src/main/java/UMC_7th/Closit/domain/user/repository/BlockRepository.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
Labels: 🐛bug, 🚨hotfix
