Repository UMC-Closit/BackEnd, pull requests merged in 2025-04, with the labels that each got.

#212 feat: 소셜 로그인 추가
  build.gradle
  src/main/java/UMC_7th/Closit/domain/user/controller/UserAuthController.java
  src/main/java/UMC_7th/Closit/domain/user/dto/OAuthLoginRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/user/entity/GoogleUserInfo.java
  src/main/java/UMC_7th/Closit/domain/user/entity/OAuthUserInfo.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/service/GoogleOAuthService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC_7th/Closit/global/common/SocialLoginType.java
  src/main/java/UMC_7th/Closit/security/SecurityConfig.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtTokenProvider.java
Labels: ✨feature

#217 refactor: 태그 글자 수 제한 (20자)
  src/main/java/UMC_7th/Closit/domain/post/dto/PostRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ♻️refactor

#218 refactor: 배틀 신청 로직 수정
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleController.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Battle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/ChallengeBattle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Status.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/ChallengeBattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/notification/entity/NotificationType.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandService.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ♻️refactor, ✨feature

#219 feat: 배틀 조회 정렬
  .github/ISSUE_TEMPLATE/bug-report-template.md
  src/main/java/UMC_7th/Closit/ClositApplication.java
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleController.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Battle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/BattleSorting.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/BattleStatus.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/ChallengeBattle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/ChallengeStatus.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Status.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Vote.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/BattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/ChallengeBattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/scheduler/BattleScheduler.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostRequestDTO.java
Labels: ✨feature
