Repository UMC-Closit/BackEnd, pull requests merged in 2025-02, with the labels that each got.

#43 #15 feat: 게시글 관련 API 구현
  src/main/java/UMC_7th/Closit/domain/follow/repository/FollowRepository.java
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/HashTag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/ItemTag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/post/repository/BookmarkRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/HashTagRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/ItemTagRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/LikesRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostHashTagRepository.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostService.java
  src/main/java/UMC_7th/Closit/domain/user/repository/UserRepository.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#41 #21 fix: 배틀 생성 및 투표 기능 API 수정
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleCommentController.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleCommentConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Battle.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Vote.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleCmtService/BattleCmtCommandService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleCmtService/BattleCmtCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleCmtService/BattleCmtQueryService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleCmtService/BattleCmtQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#44 #16 feat: 좋아요 관련 API 구현
  src/main/java/UMC_7th/Closit/domain/post/controller/LikeController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/LikeConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/LikeRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/LikeResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Likes.java
  src/main/java/UMC_7th/Closit/domain/post/repository/LikeRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeService.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/repository/UserRepository.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#47 #23 feat: 북마크 관련 API 구현
  src/main/java/UMC_7th/Closit/domain/post/controller/BookmarkController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/BookmarkConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/BookmarkRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/BookmarkResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Bookmark.java
  src/main/java/UMC_7th/Closit/domain/post/repository/BookmarkRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkService.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#49 #24 feat: 댓글 관련 API 구현
  src/main/java/UMC_7th/Closit/domain/post/controller/CommentController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/CommentConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/CommentRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/CommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/repository/CommentRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentCommandService.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#52 #22 feat: 투표 조회 API
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleController.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Battle.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/VoteRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/global/config/AmazonConfig.java
  src/main/java/UMC_7th/Closit/global/s3/AmazonS3Manager.java
Labels: ✨feature

#54 #27 Deploy: CI/CD + Docker 자동 배포
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/UMC_7th/Closit/domain/notification/controller/NotificationController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/BookmarkController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/CommentController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/LikeController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserAuthController.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC_7th/Closit/global/config/AmazonConfig.java
  src/main/java/UMC_7th/Closit/global/s3/AmazonS3Manager.java
Labels: 👷ci

#59 #26 feat: 알림 관련 API
  .gitignore
  src/main/java/UMC_7th/Closit/domain/follow/entity/Follow.java
  src/main/java/UMC_7th/Closit/domain/follow/service/FollowCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/mission/repository/MissionRepository.java
  src/main/java/UMC_7th/Closit/domain/notification/controller/NotificationController.java
  src/main/java/UMC_7th/Closit/domain/notification/converter/NotificationConverter.java
  src/main/java/UMC_7th/Closit/domain/notification/dto/NotificationRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/notification/entity/Notification.java
  src/main/java/UMC_7th/Closit/domain/notification/entity/NotificationType.java
  src/main/java/UMC_7th/Closit/domain/notification/repository/EmitterRepository.java
  src/main/java/UMC_7th/Closit/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/UMC_7th/Closit/domain/notification/repository/NotificationRepository.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandService.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiQueryService.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#63 #29 feat: 유저 프로필 이미지 업로드 구현
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/global/config/AmazonConfig.java
  src/main/java/UMC_7th/Closit/global/s3/AmazonS3Manager.java
  src/main/java/UMC_7th/Closit/security/SecurityUtil.java
Labels: ✨feature

#64 #28 refactor: 배틀 및 투표 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleCommentController.java
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleController.java
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleLikeController.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleCommentConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleLikeConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleLikeDTO/BattleLikeRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleLikeDTO/BattleLikeResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/entity/Battle.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/BattleRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleCmtService/BattleCmtCommandService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleCmtService/BattleCmtCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleLikeService/BattleLikeCommandService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleLikeService/BattleLikeCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ♻️refactor

#70 #34 fix: user id 반환값 추가
  src/main/java/UMC_7th/Closit/domain/user/dto/JwtResponse.java
  src/main/java/UMC_7th/Closit/domain/user/dto/RegisterResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
Labels: 🚨hotfix

#73 #25 feat: 오늘의 옷장 api 구현
  src/main/java/UMC_7th/Closit/domain/board/entity/Board.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/controller/TodayClosetController.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/converter/TodayClosetConverter.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/dto/TodayClosetRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/dto/TodayClosetResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/entity/TodayCloset.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/repository/TodayClosetRepository.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/service/TodayClosetQueryService.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/service/TodayClosetQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/service/TodayClosetService.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/service/TodayClosetServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#75 #34 fix: URI 내 userId -> cloistId로 수정
  src/main/java/UMC_7th/Closit/domain/highlight/converter/HighlightConverter.java
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/mission/converter/MissionConverter.java
  src/main/java/UMC_7th/Closit/domain/mission/dto/MissionResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/controller/BookmarkController.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkService.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/controller/TodayClosetController.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/JwtResponse.java
  src/main/java/UMC_7th/Closit/domain/user/dto/RegisterResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/repository/UserRepository.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtAuthenticationFilter.java
Labels: 🚨hotfix

#77 #36 fix: 배틀 response userName -> clositId 반환 수정
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleCommentConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleLikeConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleLikeDTO/BattleLikeResponseDTO.java
Labels: 🚨hotfix

#79 #37 feat: API 필터 적용
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC_7th/Closit/security/SecurityConfig.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtAuthenticationFilter.java
Labels: ✨feature

#81 #38 feat: 사용자 history 조회 API
  src/main/java/UMC_7th/Closit/domain/post/controller/HistoryController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/HistoryConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/HistoryResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/HistoryQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/HistoryQueryServiceImpl.java
Labels: ✨feature

#83 #39 refactor: 배틀 조회 API 수정
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleCommentConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleLikeConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleLikeDTO/BattleLikeResponseDTO.java
Labels: ♻️refactor

#87 #40 fix: 알림 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/notification/controller/NotificationController.java
  src/main/java/UMC_7th/Closit/domain/notification/converter/NotificationConverter.java
  src/main/java/UMC_7th/Closit/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandService.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiQueryService.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiQueryServiceImpl.java
Labels: 🚨hotfix

#88 #35 좋아요 api 수정
  src/main/java/UMC_7th/Closit/domain/post/controller/LikeController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/repository/LikesRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostService.java
Labels: 🚨hotfix

#89 #41 fix: 하이라이트 관련 엔티티 및 api 수정
  src/main/java/UMC_7th/Closit/domain/highlight/controller/HighlightController.java
  src/main/java/UMC_7th/Closit/domain/highlight/controller/HighlightPostController.java
  src/main/java/UMC_7th/Closit/domain/highlight/converter/HighlightConverter.java
  src/main/java/UMC_7th/Closit/domain/highlight/converter/HighlightPostConverter.java
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightPostRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightPostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/highlight/entity/Highlight.java
  src/main/java/UMC_7th/Closit/domain/highlight/entity/HighlightPost.java
  src/main/java/UMC_7th/Closit/domain/highlight/repository/HighlightPostRepository.java
  src/main/java/UMC_7th/Closit/domain/highlight/repository/HighlightRepository.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightCommandService.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightPostCommandService.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightPostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightPostQueryService.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightPostQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC_7th/Closit/global/apiPayload/exception/handler/HighlightPostHandler.java
  src/main/java/UMC_7th/Closit/global/validation/annotation/ExistHighlightPost.java
  src/main/java/UMC_7th/Closit/global/validation/validator/HighlightPostExistValidator.java
Labels: 🚨hotfix

#91 #42 fix: 미션 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/mission/controller/MissionController.java
  src/main/java/UMC_7th/Closit/domain/mission/converter/MissionConverter.java
  src/main/java/UMC_7th/Closit/domain/mission/dto/MissionRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/mission/dto/MissionResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/mission/entity/Mission.java
  src/main/java/UMC_7th/Closit/domain/mission/entity/MissionStatus.java
  src/main/java/UMC_7th/Closit/domain/mission/repository/MissionRepository.java
  src/main/java/UMC_7th/Closit/domain/mission/service/MissionCommandService.java
  src/main/java/UMC_7th/Closit/domain/mission/service/MissionCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/mission/service/MissionQueryService.java
  src/main/java/UMC_7th/Closit/domain/mission/service/MissionQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandService.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/ItemTag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/global/validation/annotation/ExistMission.java
  src/main/java/UMC_7th/Closit/global/validation/validator/MissionExistValidator.java
Labels: 🚨hotfix

#93 #43 feat: 사용자 정보 수정 API 구현
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#98 #46 fix: 댓글 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleService/BattleCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/controller/CommentController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/CommentConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/CommentRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/CommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: 🚨hotfix

#100 #47 fix: 좋아요, 게시글 userId->clositId 수정
  src/main/java/UMC_7th/Closit/domain/post/controller/LikeController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/LikeConverter.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/LikeRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/LikeResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Hashtag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/ItemTag.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeService.java
  src/main/java/UMC_7th/Closit/domain/post/service/LikeServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
Labels: 🚨hotfix

#106 #105 fix: refresh token 인증 안하게 수정
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
Labels: 🚨hotfix

#107 #99 feat: 최근 게시물 조회 API
  src/main/java/UMC_7th/Closit/domain/post/repository/PostRepository.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
Labels: ✨feature

#108 #103 fix: 배틀 좋아요 조회 API 수정
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
Labels: 🚨hotfix

#109 #44 fix: 미션 알림 API 수정
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandService.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Post.java
  src/main/java/UMC_7th/Closit/domain/post/repository/PostRepository.java
Labels: 🚨hotfix

#110 #45 fix: 팔로우 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/follow/controller/FollowController.java
  src/main/java/UMC_7th/Closit/domain/follow/converter/FollowConverter.java
  src/main/java/UMC_7th/Closit/domain/follow/dto/FollowRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/follow/dto/FollowResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/follow/entity/Follow.java
  src/main/java/UMC_7th/Closit/domain/follow/repository/FollowRepository.java
  src/main/java/UMC_7th/Closit/domain/follow/service/FollowCommandService.java
  src/main/java/UMC_7th/Closit/domain/follow/service/FollowCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/controller/LikeController.java
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/LikeConverter.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/LikeRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostService.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
Labels: 🚨hotfix

#114 fix: Dockerfile 한국 시간 설정 코드 추가
  Dockerfile
Labels: 👷ci, 🚨hotfix

#115 fix: 현재 시간 설정 추가
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🐛bug, 👷ci

#116 fix: application.yml 수정 후 테스트
  src/main/java/UMC_7th/Closit/domain/user/controller/UserAuthController.java
Labels: 👷ci

#117 #111 fix: 배틀 좋아요 삭제 API 수정
  src/main/java/UMC_7th/Closit/domain/battle/controller/BattleLikeController.java
  src/main/java/UMC_7th/Closit/domain/battle/repository/BattleLikeRepository.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleLikeService/BattleLikeCommandService.java
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleLikeService/BattleLikeCommandServiceImpl.java
Labels: 🚨hotfix

#119 #118 refactor: 사용자의 최근 게시물 조회 API 수정
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
Labels: ♻️refactor

#121 #112 fix: post 목록 조회 시 모든 데이터가 정상적으로 보이도록 수정
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostService.java
Labels: 🚨hotfix

#122 fix: jebal
  src/main/java/UMC_7th/Closit/ClositApplication.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtTokenProvider.java
Labels: 👷ci, 🚨hotfix

#125 #123 fix: clositId로 로그인하는 것으로 수정
  src/main/java/UMC_7th/Closit/domain/user/dto/LoginRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
Labels: 🚨hotfix

#126 #120 fix: 정화에게 토스️‍🔥
  src/main/java/UMC_7th/Closit/domain/post/controller/BookmarkController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/BookmarkConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/BookmarkRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/BookmarkResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkService.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkServiceImpl.java
Labels: 🚨hotfix

#130 #127 fix: 알림 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/notification/repository/NotificationRepository.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiQueryServiceImpl.java
Labels: 🐛bug, ♻️refactor

#133 fix: log 수정 및 허용 시간 1분으로 변경
  src/main/java/UMC_7th/Closit/security/jwt/JwtAuthenticationFilter.java
  src/main/java/UMC_7th/Closit/security/jwt/JwtTokenProvider.java
Labels: 🚨hotfix

#136 #135 refactor: 북마크 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/post/controller/BookmarkController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/BookmarkConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/BookmarkResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/repository/BookmarkRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkService.java
  src/main/java/UMC_7th/Closit/domain/post/service/BookmarkServiceImpl.java
Labels: ♻️refactor

#141 #139 refactor: 오늘의 옷장 api 수정
  src/main/java/UMC_7th/Closit/domain/todaycloset/converter/TodayClosetConverter.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/dto/TodayClosetResponseDTO.java
Labels: ♻️refactor

#146 #145 hotfix: jsonformat 추가
  src/main/java/UMC_7th/Closit/domain/follow/dto/FollowResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/todaycloset/dto/TodayClosetResponseDTO.java
Labels: 🚨hotfix

#147 hotfix: jsonformat 추가
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightResponseDTO.java
Labels: 🚨hotfix

#148 #142 feat: 메일 인증 코드 전송 api 구현
  build.gradle
  src/main/java/UMC_7th/Closit/domain/mail/controller/MailController.java
  src/main/java/UMC_7th/Closit/domain/mail/service/MailService.java
  src/main/java/UMC_7th/Closit/security/SecurityConfig.java
Labels: ✨feature

#150 #149 fix: 배틀 댓글 삭제 API 수정
  src/main/java/UMC_7th/Closit/domain/battle/service/BattleCmtService/BattleCmtCommandServiceImpl.java
Labels: 🚨hotfix

#155 #154 fix: 토큰 오차 범위 허용 제거
  src/main/java/UMC_7th/Closit/security/jwt/JwtTokenProvider.java
Labels: 🚨hotfix

#153 #151 hotfix: 사용자 정보 조회 api 수정
  src/main/java/UMC_7th/Closit/domain/follow/repository/FollowRepository.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
  src/main/java/UMC_7th/Closit/domain/user/converter/UserConverter.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryService.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserQueryServiceImpl.java
Labels: 🚨hotfix

#156 #152 fix: 알림 이미지 관련 API 수정
  src/main/java/UMC_7th/Closit/domain/notification/converter/NotificationConverter.java
  src/main/java/UMC_7th/Closit/domain/notification/entity/Notification.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
Labels: 🚨hotfix

#157 hotfix: clositId 삭제
  src/main/java/UMC_7th/Closit/domain/user/dto/UserRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserAuthServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/service/UserCommandServiceImpl.java
Labels: 🚨hotfix

#159 #158 fix: 알림 senderId 오류
  src/main/java/UMC_7th/Closit/domain/notification/converter/NotificationConverter.java
  src/main/java/UMC_7th/Closit/domain/notification/dto/NotificationRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/notification/service/NotiCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/user/controller/UserController.java
Labels: 🐛bug, 🚨hotfix

#162 #161 fix: battle comment 생성 api response에 clositId 추가
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleCommentConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentResponseDTO.java
Labels: 🚨hotfix

#168 #166 fix: 북마크 목록 조회 API 수정
  src/main/java/UMC_7th/Closit/domain/post/converter/BookmarkConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/BookmarkResponseDTO.java
Labels: 🚨hotfix

#169 #165 fix: 하이라이트 목록 조회 api 수정
  src/main/java/UMC_7th/Closit/domain/highlight/controller/HighlightController.java
  src/main/java/UMC_7th/Closit/domain/highlight/converter/HighlightConverter.java
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightResponseDTO.java
Labels: 🚨hotfix

#172 #171 fix: jsonformat 추가
  src/main/java/UMC_7th/Closit/domain/highlight/dto/HighlightResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/user/dto/UserResponseDTO.java
Labels: 🚨hotfix

#174 #170 fix: 배틀 게시글 목록 이미지 반환
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleCommentConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/converter/BattleLikeConverter.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleCmtDTO/BattleCommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleDTO/BattleResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/battle/dto/BattleLikeDTO/BattleLikeResponseDTO.java
Labels: 🚨hotfix

#177 #175 fix: 하이라이트 삭제를 post id로 하는 것으로 수정
  src/main/java/UMC_7th/Closit/domain/highlight/controller/HighlightController.java
  src/main/java/UMC_7th/Closit/domain/highlight/entity/Highlight.java
  src/main/java/UMC_7th/Closit/domain/highlight/repository/HighlightRepository.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightCommandService.java
  src/main/java/UMC_7th/Closit/domain/highlight/service/HighlightCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: 🚨hotfix

#179 #178 fix: 특정 게시글 조회에 isHighlighted 필드 추가하기
  src/main/java/UMC_7th/Closit/domain/highlight/repository/HighlightRepository.java
  src/main/java/UMC_7th/Closit/domain/post/converter/PostConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/PostResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
Labels: 🚨hotfix

#182 #180 fix: post 단일 조회 api 수정
  src/main/java/UMC_7th/Closit/domain/post/controller/PostController.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryService.java
  src/main/java/UMC_7th/Closit/domain/post/service/PostQueryServiceImpl.java
Labels: 🚨hotfix
