Repository UMC-Closit/BackEnd, pull requests merged in 2025-06, with the labels that each got.

#261 fix: CorsConfig 설정
  src/main/java/UMC_7th/Closit/global/config/CorsConfig.java
  src/main/java/UMC_7th/Closit/global/config/WebConfig.java
  src/main/java/UMC_7th/Closit/security/SecurityConfig.java
Labels: 🐛bug

#271 chore: coderabbit 설정
  .coderabbit.yaml
Labels: ✨feature, ⚙️setting

#258 feat: 대댓글 기능 구현
  src/main/java/UMC_7th/Closit/domain/post/controller/CommentController.java
  src/main/java/UMC_7th/Closit/domain/post/converter/CommentConverter.java
  src/main/java/UMC_7th/Closit/domain/post/dto/CommentRequestDTO.java
  src/main/java/UMC_7th/Closit/domain/post/dto/CommentResponseDTO.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Comment.java
  src/main/java/UMC_7th/Closit/domain/post/repository/CommentRepository.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentCommandServiceImpl.java
  src/main/java/UMC_7th/Closit/domain/post/service/CommentQueryServiceImpl.java
  src/main/java/UMC_7th/Closit/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#277 fix: 사용자 탈퇴 오류
  src/main/java/UMC_7th/Closit/domain/post/entity/Comment.java
  src/main/java/UMC_7th/Closit/domain/post/entity/Likes.java
  src/main/java/UMC_7th/Closit/domain/user/entity/User.java
Labels: 🐛bug
